language: objective-c

osx_image: xcode8
env:
  matrix:
    - DANGER=1
    - OS="iOS"
    - OS="OSX"
    - OS="watchOS"
    - OS="tvOS"

notifications:
  slack: rxswift:3ykt2Z61f8GkdvhCZTYPduOL
  email: false

script: 
  - if [ "${OS}" == "" ]; then
       bundle exec danger --verbose;
    else
      xcodebuild -version;
      xcodebuild -showsdks;
      ./scripts/all-tests.sh "${OS}";
    fi

